name: Build and Deploy GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Mingw-W64 Image'
            run: |
              docker build . --tag ghcr.io/sampletext32/mingw-w64:12.0.0
              docker push ghcr.io/sampletext32/mingw-w64:12.0.0