name: Docker

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build MinGW Image'
        run: |
          docker build -f .Dockerfile . -t ghcr.io/sampletext32/mingw-w64-docker:v12.0.0

      - name: 'Push Image'
        run: |
          docker push ${env.REGISTRY}/sampletext32/mingw-w64-docker:v12.0.0
